# Generated by Django 3.1.4 on 2020-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201212_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='YAYIN DURUMU'),
        ),
    ]
