# Generated by Django 3.1.4 on 2020-12-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_carpet_ispublished'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50, verbose_name='KÖY FOTOĞRAFI')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='EKLENME TARİHİ')),
                ('isPublished', models.BooleanField(default=True, verbose_name='YAYIN DURUMU')),
            ],
        ),
    ]
